resmgr: implement directory resources, fix #691
bertsky/core pull request #3
Opened 2022-02-13 16:40 UTC by kba

Here's an idea on how to support directories as resources.

PR against OCR-D/core#792 for easier readability.

It's currently treating `file` resources as potential file or directory resources. We might want to introduce a real `--resource-type dir` resource type to reduce the number of if-else-clauses and for consistency.

2022-02-13 22:28 UTC, bertsky approved these changes
Excellent!

2022-02-13 22:28 UTC, bertsky commented on ocrd/ocrd/resource_manager.py
> +        print(Path(res_filename).exists())
Leftover from debugging?
```suggestion
```

2022-02-14 08:29 UTC, kba commented
> We might want to introduce a real `--resource-type dir` resource type to reduce the number of if-else-clauses and for consistency.

@bertsky what about this? I tend to do it like this, also to align with the proposed spec change.

2022-02-14 11:24 UTC, bertsky commented
> > We might want to introduce a real `--resource-type dir` resource type to reduce the number of if-else-clauses and for consistency.
> 
> what about this? I tend to do it like this, also to align with the proposed spec change.

Sorry, I did not see the connection right away. 

In `cli.resmgr.download`, we already look up the `resource_type` in `resdict`, and use the CLI option for unknown resources – perhaps in the latter case we could even try keeping the type ambiguous (to have it auto-detected by `OcrdResourceManager.download`). But we do not pass that info down to `OcrdResourceManager.add_to_user_database` yet.

In `OcrdResourceManager.download`, the default is `file` (which, again, could perhaps be auto-detected). But we do not pass that down to `download_impl` and `copy_impl`. 

So AFAICS we have some ambiguity here: what if further down the `is_dir()` does not match the `resource_type`?

2022-02-19 01:38 UTC, bertsky commented on ocrd/ocrd/cli/resmgr.py
> +@click.option('-P', '--path-in-archive', help='Path to extract in case of archive type', default='.'),
typo:
```suggestion
@click.option('-P', '--path-in-archive', help='Path to extract in case of archive type', default='.')
```

2022-02-19 01:47 UTC, bertsky commented
> So AFAICS we have some ambiguity here: what if further down the `is_dir()` does not match the `resource_type`?

Meaning: better than require explicit typing and then having to deal with ambiguity would be to allow implicit typing (with early auto-detection).

But another feat that is still missing here pragmatically: we need a way to migrate existing `resources.yml` that users have installed! (But perhaps better than a hard change in the FS – which will only work with the newest core from then on – would be to tolerate the old values `tarball` and `github-dir` for a while.)

2022-02-19 01:54 UTC, bertsky requested changes

2022-02-19 01:54 UTC, bertsky commented on ocrd/ocrd/resource_manager.py
> +                with open(child_dst, 'wb') as f_out, open(child, 'rb') as f_in:
That's not recursive, though: If the source directory contains subdirectories, this fails:
```
ocrd resmgr download -t directory -n ocrd_anybaseocr/seg_model ocrd-anybaseocr-tiseg seg_model
02:48:53.405 INFO ocrd.cli.resmgr - No resources found in registry
02:48:53.405 INFO ocrd.cli.resmgr - Copying unregistered resource 'seg_model' (ocrd_anybaseocr/seg_model)
02:48:53.429 INFO ocrd.resource_manager._copy_impl - Copying /ocrd_all/ocrd_anybaseocr/seg_model to /.local/share/ocrd-resources/ocrd-anybaseocr-tiseg/seg_model
02:48:53.429 INFO ocrd.resource_manager._copy_impl - Copying recursively from /ocrd_all/ocrd_anybaseocr/seg_model to /.local/share/ocrd-resources/ocrd-anybaseocr-tiseg/seg_model
Traceback (most recent call last):
  File "/bin/ocrd", line 8, in <module>
    sys.exit(cli())
  File "/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/lib/python3.6/site-packages/ocrd/cli/resmgr.py", line 146, in download
    progress_cb=lambda delta: bar.update(delta)
  File "/lib/python3.6/site-packages/ocrd/resource_manager.py", line 274, in download
    self._copy_impl(url, fpath, progress_cb)
  File "/lib/python3.6/site-packages/ocrd/resource_manager.py", line 222, in _copy_impl
    with open(child_dst, 'wb') as f_out, open(child, 'rb') as f_in:
IsADirectoryError: [Errno 21] Is a directory: '/ocrd_all/ocrd_anybaseocr/seg_model/variables'
```

IMO the only way to make this work is by encapsulating both conditional branches into a single function that can call itself recursively.

2024-06-06 14:20 UTC, bertsky commented
Whoops!

I was not aware this branch still had relevance. I was just going through my fork's branches and deleted some – it did not indicate this.

Do you recall if this is still relevant?

2024-06-06 15:34 UTC, kba commented
It depends, I think the reason for this was that 

```
ocrd resmgr download -a -n ~/.local/share/ocrd-resources/ocrd-origami-segment/bbz ocrd-origami-segment bbz2
```

failed for you in https://github.com/OCR-D/core/issues/691#issuecomment-1038152665 - if that is now working I guess it's obsolete.

2024-06-06 15:41 UTC, bertsky commented
> if that is now working I guess it's obsolete.

Unfortunately, it's not:
```
  File "/ocrd_all/core/build/__editable__.ocrd-2.65.0-py3-none-any/ocrd/cli/resmgr.py", line 155, in download
    fpath = resmgr.download(
  File "/ocrd_all/core/build/__editable__.ocrd-2.65.0-py3-none-any/ocrd/resource_manager.py", line 314, in download
    self._copy_impl(url, fpath, progress_cb)
  File "/ocrd_all/core/build/__editable__.ocrd-2.65.0-py3-none-any/ocrd/resource_manager.py", line 257, in _copy_impl
    with open(child_dst, 'wb') as f_out, open(child, 'rb') as f_in:
IsADirectoryError: [Errno 21] Is a directory: '~/.local/share/ocrd-resources/ocrd-origami-segment/bbz/v3'
```

But I must confess I don't even recall our attempts here...

2024-06-06 15:48 UTC, bertsky commented
I managed to reinstate the PR, but since the original one was abandoned in favour of OCR-D/core#800 you should perhaps (update and) redirect against master yourself.

That said, my review still stands to reason, but I'll have to give it a closer look myself...

2024-06-06 17:23 UTC, bertsky commented
Okay, so this PR now seems pretty useless, as it has nothing new over upstream master.

I opened a dedicated issue under https://github.com/OCR-D/core/issues/1237

2024-06-06 17:23 UTC, closed without merging